# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os,shutil
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow
from pathlib import Path
import sys
import subprocess
import paramiko
import stat
import open3d as o3d
from PyQt5.QtCore import Qt

#from win_wsl import clear_folder


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
        self.retranslateUi(self)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(748, 691)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Perpetua")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setMouseTracking(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("QFrame{\n"
"    border-color: rgb(0, 0, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(30, 19, 30, 19)
        self.horizontalLayout_2.setSpacing(80)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(134, 134, 134);\n"
"border:none;\n"
"border-radius:7px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/photo-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(134, 134, 134);\n"
"border:none;\n"
"border-radius:7px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(134, 134, 134);\n"
"border:none;\n"
"border-radius:7px;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(134, 134, 134);\n"
"border:none;\n"
"border-radius:7px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
"    border-color: rgb(0, 0, 0);\n"
"}")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 724, 462))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Automatic 3-D reconstruction system"))
        self.pushButton.setText(_translate("MainWindow", "Start shooting"))
        self.pushButton_2.setText(_translate("MainWindow", "Save images"))
        self.pushButton_3.setText(_translate("MainWindow", "Reconstruction"))
        self.pushButton_4.setText(_translate("MainWindow", "Point cloud display"))
        self.pushButton.clicked.connect(self.photo)
        self.pushButton_2.clicked.connect(self.sftp_get_directory)
        self.pushButton_3.clicked.connect(self.reconstruction)
        self.pushButton_4.clicked.connect(self.showply)

    def clear_folder(folder_path):   #清空文件夹
        import os, shutil
        if not os.path.exists(folder_path):
            return
        for f in os.listdir(folder_path):
            p = os.path.join(folder_path, f)
            if os.path.isfile(p) or os.path.islink(p):
                os.unlink(p)
            else:
                shutil.rmtree(p)
    #采集图像
    def photo(self):
        self.textBrowser.setText("We are about to start collecting images, please be patient and wait...\n")
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        # 连接到树莓派
        ssh.connect('192.168.137.129', username='ubuntu', password='ubuntu')

        # 执行命令
        stdin, stdout, stderr = ssh.exec_command('sudo -S python3 paper.py')

        # 提供 sudo 密码
        stdin.write('ubuntu' + '\n')
        stdin.flush()

        text1=stdout.read().decode()
        self.textBrowser.append(text1)

        # stdin, stdout, stderr = ssh.exec_command('python3 result0.py')
        # print(stdout.read().decode())
        # print(stderr.read().decode())

        ssh.close()

    #在textBrose中实时显示系统信息
    def printf(self, mes):
        self.textBrowser.append(mes)  # 在指定的区域显示提示信息
        self.cursot = self.textBrowser.textCursor()
        self.textBrowser.moveCursor(self.cursot.End)
        QtWidgets.QApplication.processEvents()


    #保存图片
    def sftp_get_directory(self):
        # 建立SFTP连接
        remote_dir='/home/images'
        local_dir=r'\\wsl.localhost\Ubuntu-22.04\home\wensyu\DetectorFreeSfM\SfM_dataset\example_dataset\example_scene\images'
        image_dir=r'images'
        transport = paramiko.Transport(('192.168.137.129', 22))
        transport.connect(username='ubuntu', password='ubuntu')
        sftp = paramiko.SFTPClient.from_transport(transport)
        #保存文件夹中的每一张图片
        def download_dir(remote_dir, local_dir):
            if not os.path.exists(local_dir):
                os.makedirs(local_dir)
            for item in sftp.listdir_attr(remote_dir):
                remote_path = remote_dir + '/' + item.filename
                local_path = os.path.join(local_dir, item.filename)
                # if paramiko.S_ISDIR(item.st_mode):
                #     download_dir(remote_path, local_path)
                # else:
                sftp.get(remote_path, local_path)


        download_dir(remote_dir, local_dir)
        download_dir(remote_dir, image_dir)
        # 关闭SFTP连接
        sftp.close()
        transport.close()
        self.textBrowser.append("图片已保存到本地")



    #重建过程
    def reconstruction(self):
        res_dir = r'result/sparse'
        res_dense_dir = r'result/dense'
        if not os.path.exists(res_dense_dir):
            os.makedirs(res_dense_dir)
        #清空原来的文字
        self.textBrowser.clear()
        cmd = (
            'source /root/anaconda3/etc/profile.d/conda.sh && '
            'conda activate detectorfreesfm && '
            'cd /home/wensyu/DetectorFreeSfM && '
            'python eval_dataset.py +demo=dfsfm.yaml'
            # 'python eval_dataset.py'
        )
        #执行Python自动化脚本

       # srecon = subprocess.Popen([r"MvgMvsPipelineV1.py",
       #                                r"images",
       #                                r"res"], shell=True,stdout=subprocess.PIPE,text=True)

        #output, error = subprocess.communicate()
        srecon = subprocess.Popen(
        ["wsl", "-d", "Ubuntu-22.04", "bash", "-c", cmd],shell=True,stdout=subprocess.PIPE,text=True
       # check=True,
        #capture_output=True,
        #text=True,
        #encoding="utf-8",
        #errors="replace"
    )

    # output = srecon.stdout.read().decode()
        # self.printf(output)
        # srecon.wait()
        while True:
            output = srecon.stdout.readline()
            if output == '' and srecon.poll() is not None:
                break
            if output:
                self.printf(output.strip())

        #创建文件夹用于dfsfm->mvs
        if not os.path.exists(res_dir):
            os.makedirs(res_dir)
        else:
            shutil.rmtree(res_dir)
            os.makedirs(res_dir, exist_ok=True)

        #复制bin文件到此项目的res/sparse中
        src = Path(r"\\wsl.localhost\Ubuntu-22.04\home\wensyu\DetectorFreeSfM\SfM_dataset\example_dataset\example_scene\DetectorFreeSfM_loftr_official_coarse_fine__scratch_no_intrin\model_refined_0")
        dst = Path(r"result/sparse")

        dst.mkdir(parents=True, exist_ok=True)

        for item in src.iterdir():
            target = dst / item.name
            if item.is_dir():
                shutil.copytree(item, target, dirs_exist_ok=True)
            else:
                shutil.copy2(item, target)

        #用bin文件进行mvs
        p1 = subprocess.Popen(
            [
                r"bin\MVS\InterfaceCOLMAP.exe",
                "-i", r"result",
                "-o", r"result\sparse\res.mvs",
                "--image-folder", r"images"
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        p1.wait()

        p2 = subprocess.run(
            [r".\bin\MVS\DensifyPointCloud.exe",
             "-i", r"result\sparse\res.mvs",
             "-o", r"result\dense\dense_pointcloud"
             ],
            capture_output=True,
            text=True
        )
        p2.wait()




        self.textBrowser.append("Reconstruction finished!")

        srecon.wait()


    #显示点云
    def showply(self):
        ply_file_path = r"result\dense\dense_pointcloud.ply"
        point_cloud = o3d.io.read_point_cloud(ply_file_path)

        vis = o3d.visualization.Visualizer()
        vis.create_window(window_name='Point Cloud', width=1024, height=768)

        # 添加点云并渲染
        vis.add_geometry(point_cloud)
        vis.run()
        vis.destroy_window()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow1 = QMainWindow()     #MainWindow1可修改
    ui = Ui_MainWindow()             #可修改
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec_())


